### ISSUE TITLE
custom dataset

### ISSUE THREAD

**Issue by delgerdalai** [tugstugi/pytorch-dc-tts#1]
Сайн уу? 

Dataset -н wav файлууд заавал өгүүлбэрээр төгсөж байх ёстой юу? 2 өгүүлбэр, эсвэл урт өгүүлбэрүүдийг хоёр, гурван хэсэг болгон хуваасан байж болох уу? training-д ямар нэг нөлөө байгаа болов уу?

Баярлалаа

**Comment by tugstugi** [comment]
Сайн байна уу? Нэг их сүртэй нөлөө байхгүй. Гэхдээ бүтэн өгүүлбэр юм уу таслалаар тасалж оруулбал prosody илүү сайн сурах байх. Өгүүлбэр бас дэндүү урт байж болохгүй тэгвэл training time чинь ихсэнэ.
