### ISSUE TITLE
colab demo RuntimeError

### ISSUE THREAD

**Issue by b29b** [tugstugi/pytorch-dc-tts#11]
tried to run [this](https://colab.research.google.com/github/tugstugi/pytorch-dc-tts/blob/master/notebooks/EnglishTTS.ipynb)
last step segment of prepare model gives me this error:
`RuntimeError: storage has wrong size: expected 4541342186092732661 got 512`

**Comment by tugstugi** [comment]
Can't reproduce it. It is working. Make "Facetory Reset Runtime" and "Run All".
