### ISSUE TITLE
transfer learning ljspeech

### ISSUE THREAD

**Issue by fivevolt** [tugstugi/pytorch-dc-tts#12]
First of all thank you for the repository, the result is really awesome.
Is it possible to transfer learning from pretrained models (ljspeech) into my recording data?

**Comment by tugstugi** [comment]
If it is english it is possible, but requires some code. You have to modify `train-text2mel.py` and `train-ssrn.py` to include such code:
```
text2mel.load_state_dict(torch.load('pretrained_ljspeech_text2mel.pth').state_dict())
```
and
```
ssrn.load_state_dict(torch.load('pretrained_ljspeech_ssrn.pth').state_dict())
```

**Comment by HiraJamshed20** [comment]
Where would this piece of code be added?
