### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by HiraJamshed20** [tugstugi/pytorch-dc-tts#14]
I am not sure how the code would run with a new dataset and what the dataset should look like in order to be trained on it?

**Comment by tugstugi** [comment]
It should have the same format as the LJSpeech dataset: https://keithito.com/LJ-Speech-Dataset/

**Comment by HiraJamshed20** [comment]
Okay and I also see that in the code, only two choices for the dataset are given. If I am to make a new one, then I should exapnd the choices and add my dataset name to that yes?

**Comment by HiraJamshed20** [comment]
> It should have the same format as the LJSpeech dataset: https://keithito.com/LJ-Speech-Dataset/
Okay and I also see that in the code, only two choices for the dataset are given. If I am to make a new one, then I should exapnd the choices and add my dataset name to that yes?

**Comment by HiraJamshed20** [comment]
> It should have the same format as the LJSpeech dataset: https://keithito.com/LJ-Speech-Dataset/

Okay and I also see that in the code, only two choices for the dataset are given. If I am to make a new one, then I should exapnd the choices and add my dataset name to that yes?

**Comment by tugstugi** [comment]
if you don't want change any code then imitiate really LJSpeech and use the ljspeech option. That is it. Otherwise you have to change the code to add your custom dataset.
