### ISSUE TITLE
Empty speech output (some sentences synthesize and others don't)

### ISSUE THREAD

**Issue by lorinczb** [tugstugi/pytorch-dc-tts#16]
Hello!

I have seen a similar problem among the issues with the WaveGlow model, but I am running the original code, on a Romanian dataset with a sampling rate of 16000. Tried both the gated_conv and highway options for the text2mel_basic_block.

After the model has been training for 300K steps, some of the sentences are synthesized correctly, while others are completely blank, it generates a silent audio of a few seconds. I have copied some of the attention, mel and mag files that didn't synthesize and added some examples that were correctly synthesized. (https://drive.google.com/drive/folders/1Mq6_xub9urzJxXAXI_HVaws0sZZqrg8X?usp=sharing)

Do you have any ideas why that might be happening? 

(I have added a multi-speaker option to your code that I can also share, it seems to be learning, but the same thing happens, some test sentences are synthesized, while others not, and it seems to be quite random.)

Thanks in advance!

**Comment by tugstugi** [comment]
@lorinczb you said you have solved the issue in https://github.com/lorinczb/pytorch-dc-tts

So I am closing this ticket.
