### ISSUE TITLE
How to train a Tibetan-TTS model

### ISSUE THREAD

**Issue by Joee1995** [tugstugi/pytorch-dc-tts#4]
Thx first for this excellent project and your patience. I have already finished the training of the Mongolian-TTS model which works really well. It's cool! 

And, what should I do if I want to train a Tibetan-TTS model based on this project? Can u give me some suggestions？

Sorry for this question, but I'm actually a novice. Thx in advance!

**Comment by tugstugi** [comment]
You have to create a Tibetan dataset which should have same format as the LJSpeech: https://keithito.com/LJ-Speech-Dataset/

It means you need many audio snippets up to 10 seconds and also its transcriptions. For Mongolian, there wasn't any dataset. So I had to create one (MBSpeech) from the Mongolian Bible audio book. For manually splitting 5 hours from the Bible audio book and transcribing it, took me around 30 hours.

If you have created a such dataset in LJSpeech format, you can also use it for all other open source TTS projects such as https://github.com/Rayhane-mamah/Tacotron-2 and https://github.com/NVIDIA/tacotron2

They will have also better audio quality than this project. The only advantage of pytorch-dc-tts is, it is fully convolutional and so really fast to get results. Change both parameters `text2mel_max_iteration` and `ssrn_max_iteration` to 50.000 or even lower, then you will the feedback in few hours whether your dataset is working or not.
