### ISSUE TITLE
how to train language require tokenization

### ISSUE THREAD

**Issue by kyspeech** [tugstugi/pytorch-dc-tts#7]
@tugstugi thanks for this repo and the sharing.

I am trying to train japanese but it wasn't in good quality, for japanese it would need to tokenize first ありがとうございます as there are not white space between the words

I copy a file from mb_speech.py, where I tokenize the words and then update the vocab string in the speech.py model with all possible characters in the corpus. However, after 12 hours of training, it couldn't produce results in japanese. If there should be any extra steps to follow? Thanks.

**Comment by tugstugi** [comment]
hi @kyspeech,

this repo is now not activily maintened. You can try other open source TTS implementions which can produce much better audios:
* NVidia Tacotron: https://github.com/NVIDIA/tacotron2
* Rayhane Tacotron: https://github.com/Rayhane-mamah/Tacotron-2
* fatchord Tacotron: https://github.com/fatchord/WaveRNN

**Comment by tugstugi** [comment]
Have you checked the tensorboard graphs i.e. alignment graphs? If it can't learn any alignment, it can't also produce audios.

**Comment by tugstugi** [comment]
Tensorboard log directory is under `path/to/project/logdir`.

**Comment by kyspeech** [comment]
![image](https://user-images.githubusercontent.com/54815934/64129765-bdb34b80-cdf0-11e9-8f32-3db37efcff51.png)

@tugstugi the training result is as above, you are right, seems the alignment didn't learn, do you have idea why?

**Comment by tugstugi** [comment]
Tensorboard should have a tab called "Images". Under that, the generated spectrograms and alignments are saved. Could you check those?

**Comment by kyspeech** [comment]
![image](https://user-images.githubusercontent.com/54815934/64129967-f4d62c80-cdf1-11e9-9fa2-ac528760a797.png)

![image](https://user-images.githubusercontent.com/54815934/64129987-12a39180-cdf2-11e9-8e1a-bbb4c94d0452.png)

it's like the above images, how could i tell if it learns the alignment?

**Comment by tugstugi** [comment]
`text2mel/attention` is the alignment, actually looks good...

**Comment by tugstugi** [comment]
The trained model should be able to generate at least audible audios. What is the problem? Skipping words? Can't produce anything?

**Comment by kyspeech** [comment]
yes, the model can generate some audible audios, it's just doesn't pronounce the word well (only some audible audios) and seems skipping words too.

I will try to train with more data, as i used around 4 hours of speech, btw, which pytorch version u used? i used pytorch 1.0 and wonder if it is an issue.

**Comment by kyspeech** [comment]
also the loss_att in the tensorboard above seems fluctuating a lot? would that be an indicator of issues too?

**Comment by tugstugi** [comment]
I think the model is overfitting because of 4 hours dataset. text2mel logs should have also validation loss. If it goes up, it means that it is overfitting. Normally TTS datasets have around 20 hours. With a small dataset (6 hours), I have best luck with https://github.com/Rayhane-mamah/Tacotron-2

Could you attach a sample synthesized audio?

**Comment by kyspeech** [comment]
[download.zip](https://github.com/tugstugi/pytorch-dc-tts/files/3566905/download.zip)

here is a sample one

do u mean using https://github.com/Rayhane-mamah/Tacotron-2 would be good for small amount of data?

i like your approach using Deep Convolutional Networks with Guided Attention as it can train fast with 1 GPU and the results not bad, for Tactron-2 the training time would be much more and GPU also require higher class?

**Comment by tugstugi** [comment]
Yes, I got good results with 6 hours dataset with https://github.com/Rayhane-mamah/Tacotron-2 -> it will not skip over characters etc. But you have to be patient, it needs around 5 days to reach 150k steps.

Here is my fork for Mongolian, you can follow it: https://github.com/tugstugi/Tacotron-2
6 hours dataset will sound like here: https://colab.research.google.com/github/tugstugi/mongolian-nlp/blob/master/misc/Tacotron_MongolianTTS.ipynb

Other TTS repos like NVidia Tacotron will overfit 6 hours dataset.

**Comment by kyspeech** [comment]
got it, thanks, what about using https://github.com/fatchord/WaveRNN? as would prefer pytorch than tensorflow

**Comment by tugstugi** [comment]
I haven't trained the 6 hours dataset with fatchord's repo. So I can't say whether it will overfit or not. For fatchord, you have train not only the Tacotron but also the vocoder WaveRNN which will also take a long time.

**Comment by kyspeech** [comment]
thanks a lot @tugstugi i will try with Tacotron-2

**Comment by kenyeung128** [comment]
Btw if overfitting, I could try with a text in the training data and it shall produce good quality?

**Comment by kyspeech** [comment]
Btw if overfitting, I could try with a text in the training data and it shall produce good quality?

**Comment by tugstugi** [comment]
@kyspeech yes. If it can't reproduce good audio for the training text, you have to train longer.

**Comment by kyspeech** [comment]
![image](https://user-images.githubusercontent.com/54815934/64181376-ebec6600-ce98-11e9-88ca-aead6303b0be.png)

@tugstugi i tried to train longer with more than 10 hours of data, seems the validation loss also go flat quickly after 5k steps, is that normal?

**Comment by kyspeech** [comment]
@tugstugi got something like this with another dataset, the validation and the training loss go up, and when synthesise the audio, it has no voice, might i ask if u have any idea?

<img width="752" alt="Screenshot 2019-09-08 at 6 15 24 PM" src="https://user-images.githubusercontent.com/54815934/64486819-c4184c00-d264-11e9-9abf-344baa635dce.png">

**Comment by tugstugi** [comment]
It seems the loss is exploded? Try smaller LR. As always check your alignment graph.

**Comment by kyspeech** [comment]
![image](https://user-images.githubusercontent.com/54815934/64487061-19a22800-d268-11e9-9569-8c3e515324cb.png)

The alignment graph is as above, do u see something wrong?

**Comment by tugstugi** [comment]
If the TTS network learned something useful, the aligment graph must be diagonal.

**Comment by tugstugi** [comment]
You are training the SSRN? So there will no aligment graph. Try really a smaller LR.

**Comment by kyspeech** [comment]
yes i . am training SSRN, the Text2Mel seems okay as there is diagonal, but seems for SSRN the mags-pred is v. different than mags-true? i will try to use a small LR

**Comment by kyspeech** [comment]
and in that case, i must delete the train model and start again from scratch?

**Comment by tugstugi** [comment]
@kyspeech yes, you have to train again from scratch.

**Comment by kyspeech** [comment]
thanks @tugstugi  i will try, also i realized that i changed to a smaller batch size as gpu running out of memory

**Comment by kyspeech** [comment]
hi @tugstugi i tried to train with a smaller learning rate and longer time, but seems not improve, could you hear the attached file if u know what might go wrong?

[download (2).wav.zip](https://github.com/tugstugi/pytorch-dc-tts/files/3589508/download.2.wav.zip)

**Comment by tugstugi** [comment]
@kyspeech maybe loss exploded again? post your `mags-pred` and loss graphs.

**Comment by kyspeech** [comment]
for text-mel

![image](https://user-images.githubusercontent.com/54815934/64518085-1ff5da00-d324-11e9-9c00-65877b90dc53.png)

**Comment by kyspeech** [comment]
for ssrn 
![image](https://user-images.githubusercontent.com/54815934/64518129-34d26d80-d324-11e9-90c4-9e4eefb928a0.png)

**Comment by kyspeech** [comment]
to me, both looks ok @tugstugi ?

**Comment by tugstugi** [comment]
SSRN looks ok, but Text2Mel not, attention got problem. but atleast it should produce some audible audio.

**Comment by kyspeech** [comment]
oh which part Text2Mel not okay as in the image? and what would parameters you suggest to change? yes the audio is not audible somehow

**Comment by tugstugi** [comment]
@kyspeech Attention should be at the end a line, see here i.e. Gif from Fatchord's repo: https://github.com/fatchord/WaveRNN/blob/master/assets/training_viz.gif

Maybe your dataset got a problem? Try first LJSpeech to see if there is a version problem etc.

**Comment by kyspeech** [comment]
thanks @tugstugi will try again with another dataset, yes, i think could be the dataset has problem with the quality. If there are background noise, do you suggest to use another library to remove it first?
